name: 'Jemurai Crush'
description: 'Crush code - automate code review'
branding:
  icon: 'code'
  color: 'red'
inputs:
  dir: 
    description: 'The directory to scan'
    required: false
    default: '.'
  command:
    description: 'The command to run'
    required: false
    default: 'examine'
  debug:
    description: 'The directory to scan'
    required: false
    default: 'true'
  flags:
    description: 'Other flags'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
    - ${{ inputs.dir }}
    - ${{ inputs.debug }}
    - ${{ inputs.flags }}