image: golang:1.16

pipelines:
  default:
    - parallel:
      - step:
          name: Run Crush
          script:
            - go get -u github.com/jemurai/crush@v1.0.5
            - crush version
            - crush secrets .
            - crush files .
            - crush examine --threshold 6 --tag badwords .