name: CRUSH

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    #  schedule:
    # Runs every day At 01:00.
    #   - cron:  '0 1 * * *'    

jobs:
  crush_job:
    runs-on: ubuntu-latest
    name: Assisted code review
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Crush Scan
        uses: jemurai/crush@v1.0.3
        with:
          dir: .
          command: examine
          debug: true
          flags: '--threshold 5'